name: Build Environnement tests
on:
  push:
    branches:
      - main
jobs:
  tests_unitaires:
      name: Lancement des tests unitaires
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [12.x, 14.x, 16.x]
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'

        - name: installation des packages
          run: npm ci

        - name: Build
          run: npm run build --if-present

        - name: Tests
          run: npm test

  tests_Sonarcloud:
    name: Lancement des tests SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=devops-ripault-lairie
            -Dsonar.projectKey=alex-lri_DevOps_TP
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  tests_Trivy:
    name: Lancement des tests Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/devops_tp:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/devops_tp:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
